### ISSUE TITLE
Error header session

### ISSUE THREAD

**Issue by ghost** [sunspikes/php-amadeus#1]
Hello,

I'am french and work with Amadeus. But your class generate error for me.

``` php
 public function pnrRetrieve($pnr_id)
    {
        $params = array();
        $params['PNR_Retrieve']['retrievalFacts']['retrieve']['type'] = 2;
        $params['PNR_Retrieve']['retrievalFacts']['reservationOrProfileIdentifier']['reservation']['controlNumber'] = $pnr_id;

        $this->_data = $this->_client->__soapCall('PNR_Retrieve', $params, null,
            new \SoapHeader(Client::AMD_HEAD_NAMESPACE, 'Session', $this->_headers['Session']), $this->_headers);

        var_dump($this->_client->__getLastRequest());
        $this->debugDump($params);
    }
```

return :

99|Session|Not authenticated

or if I write this : 

``` php
 $this->_data = $this->_client->__soapCall('PNR_Retrieve', $params, null,
            new \SoapHeader(Client::AMD_HEAD_NAMESPACE, 'SessionId', $this->_headers['Session']->SessionId), $this->_headers);
```

return : 

98|Session|Bad SecurityToken

are you one idea ?

help

**Comment by yasirshah12** [comment]
Please tell me which is [YOUR_SOURCE] [YOUR_ORIGIN], [YOUR_PASSWORD], [length], [ORGANIZATION_ID]

what will put in these [] areas

 <POS>

                                <Source PseudoCityCode="officeid">

                                                <RequestorID Type="21"
ID="requestor" />

                                </Source>

                                <TPA_Extensions>

                                                <Provider>

                                                                <Name>Amadeus</Name>

                                                                <System>Test</System>

                                                                <Userid>userid</Userid>

                                                                <Password>password</Password>

                                                </Provider>

                                </TPA_Extensions>

                </POS>

**Comment by sunspikes** [comment]
@yasirshah12 for those parameters please contact Amadeus.

**Comment by yasirshah12** [comment]
please helpp..
Uncaught SoapFault exception: [Client] Function ("Security_Authenticate") is not a valid method for this service

**Comment by sunspikes** [comment]
You may be using wrong a WSDL, please see the README.

**Comment by marcosofthard** [comment]
It has the implementation of CarPushLocation and CarPushPolicy?

**Comment by Mujammil** [comment]
Hi, I am getting this error,,, "Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 33554432 bytes)" for Fare_MasterPricerTravelBoardSearch method.
set max memory size, everythig done but still this error happen.
  Could you please help.
