### ISSUE TITLE
Fare_MasterPricerTravelBoardSearch - 

### ISSUE THREAD

**Issue by Mujammil** [sunspikes/php-amadeus#10]
Hi, I am getting this error,,, "Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 33554432 bytes)" for Fare_MasterPricerTravelBoardSearch method.
set max memory size, everythig done but still this error happen.
Could you please help.

**Comment by sunspikes** [comment]
May be you should debug/profile your code for memory usage, this not seems to be an issue with this library.
