### ISSUE TITLE
93|Session|Illogical conversation & 95|Session|Inactive conversation

### ISSUE THREAD

**Issue by vishababu** [sunspikes/php-amadeus#12]
Hi,
I have work with Amadeus. In Which Scenario, the following error messages will thrown from Amadeus

93|Session|Illogical conversation & 95|Session|Inactive conversation

Can you please explain the Scaenario?
help?

**Comment by sunspikes** [comment]
It could be because you are making a call without proper authentication 

Make sure you have correct credentials and you called `SecurityAuthenticate` before your request.

I think its better you contact Amadeus if this doesn't work.
