### ISSUE TITLE
Error in fareMasterPricerTravelBoardSearch

### ISSUE THREAD

**Issue by shamank** [sunspikes/php-amadeus#2]
You are defining $travellers['I'] as INFANTS, but the docs says that it should be 'IN' instead. Is this right? I'm still adapting the method and didn't test it, but that's what the docs says. Can someone confirm it?

**Comment by sunspikes** [comment]
The is in fact an abstraction for the library and not send to the service as is. See the code  https://github.com/sunspikes/php-amadeus/blob/master/src/Command/PnrAddMultiElements.php#L45
