### ISSUE TITLE
IssueTicet

### ISSUE THREAD

**Issue by mohammad1111** [sunspikes/php-amadeus#8]
I Want IssueTicket And Email Itinary please Help Me!!
I Send This Sample But Get Error:

    <DocIssuance_IssueTicket xmlns="http://xml.amadeus.com/TTKTIQ_09_1_1A">
      <optionGroup>
        <switches>
          <statusDetails>
            <indicator>ITR</indicator>
          </statusDetails>
        </switches>
      </optionGroup>
      <otherCompoundOptions>
        <attributeDetails>
          <attributeType>ETC</attributeType>
          <attributeDescription>GF</attributeDescription>
        </attributeDetails>
      </otherCompoundOptions>
      <otherCompoundOptions>
        <attributeDetails>
          <attributeType>EMPR</attributeType>
          <attributeDescription>ticket@gmail.com</attributeDescription>
        </attributeDetails>
      </otherCompoundOptions>
    </DocIssuance_IssueTicket>

error format not valid.

--------------------------------------------------------------------------------------------------
if Send This XML send to amadeus ticket Issue But email not work

    <DocIssuance_IssueTicket xmlns="http://xml.amadeus.com/TTKTIQ_09_1_1A">
      <otherCompoundOptions>
        <attributeDetails>
          <attributeType>ETC</attributeType>
          <attributeDescription>GF</attributeDescription>
        </attributeDetails>
      </otherCompoundOptions>
 </DocIssuance_IssueTicket>
--------------------------------------------------------------------------------------------------
if Send This XML send to amadeus 

    <DocIssuance_IssueTicket xmlns="http://xml.amadeus.com/TTKTIQ_09_1_1A">
      <otherCompoundOptions>
        <attributeDetails>
          <attributeType>EMPR</attributeType>
          <attributeDescription>ticket@gmail.com</attributeDescription>
        </attributeDetails>
      </otherCompoundOptions>
 </DocIssuance_IssueTicket>

Error:BSP: "TICKETING NOT ALLOWED - PLEASE USE DIRECT DISTRIBUTION"

**Comment by sunspikes** [comment]
Please contact Amadeus for issues like this.
